"""Add is_verified to clients

Revision ID: 2a1bbe1a62c7
Revises: 54eb290dd82c
Create Date: 2025-05-02 11:07:13.035372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1bbe1a62c7'
down_revision: Union[str, None] = '54eb290dd82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('clients', 'is_verified', server_default=None)  # this is needed to remove the server default
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_verified')
    # ### end Alembic commands ###
