"""Change import of metadatas

Revision ID: 54eb290dd82c
Revises: a9c59b5a2620
Create Date: 2025-04-30 19:59:23.138454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54eb290dd82c'
down_revision: Union[str, None] = 'a9c59b5a2620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
