"""fix

Revision ID: 608fadae7a8a
Revises: 5d53234ef8b1
Create Date: 2025-05-22 13:50:33.345385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608fadae7a8a'
down_revision: Union[str, None] = '5d53234ef8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_psychologist_psychologist_id_fkey', 'client_psychologist', type_='foreignkey')
    op.create_foreign_key(None, 'client_psychologist', 'psychologists', ['psychologist_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('confirmation_requests_psychologist_id_fkey', 'confirmation_requests', type_='foreignkey')
    op.create_foreign_key(None, 'confirmation_requests', 'psychologists', ['psychologist_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint('psychologist_requests_psychologist_id_fkey', 'psychologist_requests', type_='foreignkey')
    op.create_foreign_key(None, 'psychologist_requests', 'psychologists', ['psychologist_id'], ['client_id'], ondelete='CASCADE')
    op.add_column('psychologists', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('psychologists', sa.Column('client_photo', sa.String(), nullable=True))
    op.drop_column('psychologists', 'psychologist_photo')
    op.drop_column('psychologists', 'psychologist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologists', sa.Column('psychologist_id', sa.INTEGER(), server_default=sa.text("nextval('psychologists_psychologist_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('psychologists', sa.Column('psychologist_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('psychologists', 'client_photo')
    op.drop_column('psychologists', 'client_id')
    op.drop_constraint(None, 'psychologist_requests', type_='foreignkey')
    op.create_foreign_key('psychologist_requests_psychologist_id_fkey', 'psychologist_requests', 'psychologists', ['psychologist_id'], ['psychologist_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'confirmation_requests', type_='foreignkey')
    op.create_foreign_key('confirmation_requests_psychologist_id_fkey', 'confirmation_requests', 'psychologists', ['psychologist_id'], ['psychologist_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'client_psychologist', type_='foreignkey')
    op.create_foreign_key('client_psychologist_psychologist_id_fkey', 'client_psychologist', 'psychologists', ['psychologist_id'], ['psychologist_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
