"""Add indecies to tables

Revision ID: 9864a7d414bc
Revises: aa715ba6c2f5
Create Date: 2025-05-20 16:09:34.913195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9864a7d414bc'
down_revision: Union[str, None] = 'aa715ba6c2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_client_psychologist_client_id', 'client_psychologist', ['client_id'], unique=False)
    op.create_index('idx_client_psychologist_psychologist_id', 'client_psychologist', ['psychologist_id'], unique=False)
    op.create_index('idx_client_requests_client_id', 'client_requests', ['client_id'], unique=False)
    op.create_index('idx_client_requests_status', 'client_requests', ['status'], unique=False)
    op.create_index('idx_clients_email', 'clients', ['email'], unique=False)
    op.create_index('idx_clients_login', 'clients', ['login'], unique=False)
    op.create_index('idx_confirmation_requests_client_id', 'confirmation_requests', ['client_id'], unique=False)
    op.create_index('idx_confirmation_requests_psychologist_id', 'confirmation_requests', ['psychologist_id'], unique=False)
    op.create_index('idx_notes_client_id', 'notes', ['client_id'], unique=False)
    op.create_index('idx_notes_createdAt', 'notes', ['createdAt'], unique=False)
    op.create_index('idx_psychologist_requests_client_id', 'psychologist_requests', ['client_id'], unique=False)
    op.create_index('idx_psychologist_requests_psychologist_id', 'psychologist_requests', ['psychologist_id'], unique=False)
    op.create_index('idx_psychologists_email', 'psychologists', ['email'], unique=False)
    op.create_index('idx_psychologists_login', 'psychologists', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_psychologists_login', table_name='psychologists')
    op.drop_index('idx_psychologists_email', table_name='psychologists')
    op.drop_index('idx_psychologist_requests_psychologist_id', table_name='psychologist_requests')
    op.drop_index('idx_psychologist_requests_client_id', table_name='psychologist_requests')
    op.drop_index('idx_notes_createdAt', table_name='notes')
    op.drop_index('idx_notes_client_id', table_name='notes')
    op.drop_index('idx_confirmation_requests_psychologist_id', table_name='confirmation_requests')
    op.drop_index('idx_confirmation_requests_client_id', table_name='confirmation_requests')
    op.drop_index('idx_clients_login', table_name='clients')
    op.drop_index('idx_clients_email', table_name='clients')
    op.drop_index('idx_client_requests_status', table_name='client_requests')
    op.drop_index('idx_client_requests_client_id', table_name='client_requests')
    op.drop_index('idx_client_psychologist_psychologist_id', table_name='client_psychologist')
    op.drop_index('idx_client_psychologist_client_id', table_name='client_psychologist')
    # ### end Alembic commands ###
