"""Add rejection_reason field into ClientRequest entity

Revision ID: 9ac136979b04
Revises: 444a963a63af
Create Date: 2025-05-05 12:27:13.466254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac136979b04'
down_revision: Union[str, None] = '444a963a63af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_requests', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('client_requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('client_requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_requests', 'updated_at')
    op.drop_column('client_requests', 'created_at')
    op.drop_column('client_requests', 'rejection_reason')
    # ### end Alembic commands ###
