"""Initial migration of all the entities

Revision ID: a9c59b5a2620
Revises: 
Create Date: 2025-04-30 18:06:08.426680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9c59b5a2620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birthAt', sa.DateTime(), nullable=False),
    sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('client_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('psychologists',
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birthAt', sa.DateTime(), nullable=False),
    sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('psychologist_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('psychologist_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('client_psychologist',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('client_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='request_status'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('confirmation_requests',
    sa.Column('confirmation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('confirmedAt', sa.DateTime(), nullable=True),
    sa.Column('type', postgresql.ENUM('REGISTRATION', 'PASSWORD_RESET', name='confirmation_type'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('emotions', postgresql.ENUM('AFRAID', 'ANGRY', 'ANXIOUS', 'ASHAMED', 'AWKWARD', 'BORED', 'CALM', 'CONFUSED', 'DISGUSTED', 'EXCITED', 'FRUSTRATED', 'HAPPY', 'JEALOUS', 'NOSTALGIC', 'PROUD', 'SAD', 'SATISFIED', 'SURPRISED', name='emotions'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('psychologist_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='request_status'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['psychologists.psychologist_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psychologist_requests')
    op.drop_table('notes')
    op.drop_table('confirmation_requests')
    op.drop_table('client_requests')
    op.drop_table('client_psychologist')
    op.drop_table('psychologists')
    op.drop_table('clients')
    op.drop_table('admins')
    # ### end Alembic commands ###
