"""add psychologist docs field

Revision ID: ddf6708518cb
Revises: 608fadae7a8a
Create Date: 2025-05-26 14:41:06.046684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf6708518cb'
down_revision: Union[str, None] = '608fadae7a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologists', sa.Column('psychologist_docs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychologists', 'psychologist_docs')
    # ### end Alembic commands ###
